version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: chatbot
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mynetwork

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB: "postgres://postgres:1234@db:5432/chatbot?sslmode=disable"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
