info:
  contact: {}
paths:
  /:
    get:
      description: Renders the index page
      produces:
      - text/html
      responses:
        "200":
          description: Index page
          schema:
            type: html
      summary: Index Page
      tags:
      - index
  /api/generate:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Generate content based on the given prompt
      parameters:
      - description: Prompt
        in: formData
        name: prompt
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Generated content
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GenerateContent
      tags:
      - generate
swagger: "2.0"
