definitions:
  models.Question:
    properties:
      max_length:
        type: integer
      question:
        type: string
    type: object
  models.User:
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: Renders the index page
      produces:
      - text/html
      responses:
        "200":
          description: Index page
          schema:
            type: html
      summary: Index Page
      tags:
      - index
  /api/generate:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Generate content based on the given prompt
      parameters:
      - description: Prompt
        in: formData
        name: prompt
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Generated content
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GenerateContent
      tags:
      - generate
  /api/generate/motivational_letter:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Generate a motivational letter based on user data
      parameters:
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: Age
        in: formData
        name: age
        required: true
        type: integer
      - description: University
        in: formData
        name: university
        required: true
        type: string
      - description: Country
        in: formData
        name: country
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create Motivational Letter
      tags:
      - letters
  /api/generate/python:
    post:
      consumes:
      - application/json
      description: Generate content based on the given prompt
      parameters:
      - description: Question to get answer for
        in: body
        name: question
        required: true
        schema:
          $ref: '#/definitions/models.Question'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: GenerateContent
      tags:
      - generate
  /faq:
    get:
      consumes:
      - application/json
      description: Generate content based on the given prompt
      parameters:
      - description: Question to get answer for
        in: query
        name: question
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get FAQ Answer
      tags:
      - faq
  /login:
    post:
      consumes:
      - application/json
      description: Logs in an existing user
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - Auth
  /signup:
    post:
      consumes:
      - application/json
      description: Signs up a new user
      parameters:
      - description: New user information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Sign up user
      tags:
      - Auth
swagger: "2.0"
