definitions:
  models.User:
    type: object
info:
  contact: {}
paths:
  /:
    get:
      description: Renders the index page
      produces:
      - text/html
      responses:
        "200":
          description: Index page
          schema:
            type: html
      summary: Index Page
      tags:
      - index
  /api/generate:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Generate content based on the given prompt
      parameters:
      - description: Prompt
        in: formData
        name: prompt
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: Generated content
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: GenerateContent
      tags:
      - generate
  /login:
    post:
      consumes:
      - application/json
      description: Logs in an existing user
      parameters:
      - description: User credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login user
      tags:
      - Auth
  /signup:
    post:
      consumes:
      - application/json
      description: Signs up a new user
      parameters:
      - description: New user information
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Sign up user
      tags:
      - Auth
swagger: "2.0"
